### ISSUE TITLE
тест1

### ISSUE THREAD

**Issue by denn1sam** [olehmelnyk/fl9-Questions#1]
тест1

**Comment by denn1sam** [comment]
перший комміт!

**Comment by andrii1509** [comment]
Wonderful

**Comment by SerhiiTkachenko** [comment]
Я за **GIT,** бо тут зручно буде накидувати питання і давати відповіді.
Якщо вже не знайдеться відповіді тоді це кидати в доку!! :trollface:

**Comment by olehmelnyk** [comment]
залишилось придумати, як переконати ще 200+ чоловік хочаби спробувати))

**Comment by denn1sam** [comment]
я дял групи створив таке саме репо, наша група за гіт)

**Comment by OliviaMurys** [comment]
+ за гіт бо в доці вже треш)

**Comment by SerhiiTkachenko** [comment]
**GIT** це має бути відправна точка, далі не вирішені питання ідуть в доки! :blush:

**Comment by olehmelnyk** [comment]
і тут сповіщення на пошту приходить коли задають питання або пишуть відповідь, а доки треба сидіти і постійно рефрешити))

**Comment by ipavlyuk** [comment]
Тут теж треш буде )
Якщо все ж юзати гіт для питань, тоді тут не повинно бути зайвих переписок всеодно )

**Comment by olehmelnyk** [comment]
то для тесту тільки)))

**Comment by andrii1509** [comment]
![36446279_1731820283578574_1959046050991833088_n](https://user-images.githubusercontent.com/34772397/43198893-e32c6926-9018-11e8-8646-91d6f33c716e.jpg)

**Comment by andrii1509** [comment]
![photo_2018-07-10_21-38-53 2](https://user-images.githubusercontent.com/34772397/43198964-20322e96-9019-11e8-99fb-db9ae2b20bb4.jpg)
Хто шарить той пойме)))))))))))

**Comment by andrii1509** [comment]
![photo_2018-07-10_17-50-06](https://user-images.githubusercontent.com/34772397/43199144-b27f379e-9019-11e8-9849-b9a97225894a.jpg)

**Comment by olehmelnyk** [comment]
хватить флуду) картинки то круто але треба вирішитись чи ми в то бавимся чи тримаємся гуглодоків

**Comment by pavlosuperhero** [comment]
Що таке Q/A в цілому? це типу півтори години присвячено запитанням та відповідям? Це буде відео, чи тексти?

**Comment by olehmelnyk** [comment]
на скільки я розумію - то просто викладачі в спеціальному чаті 30 хвилин будуть відповідати на питання - з гуглдоксів _або_ звідси

**Comment by dnistrova** [comment]
Яка різниця де обговорювати, куди писати питання, якщо, прочитавши 999+ повідомлень з чату в гіттері я не побачила жодної конкретики. І не знаю, чи буде на що викладачам сьогодні відповідати. Можливо після завтрішньої лекції будуть більш грунтовні питання і відповіді. Я не проти вчити всі можливі програми, інструменти і т.д.

**Comment by ipavlyuk** [comment]
Нам питання потрібно буде перенести сюди https://docs.google.com/spreadsheets/d/1gC-VaVNpKTGx-hhAtDNKPvX-U9dnLn6yOPs32hR9JmE/edit?ts=5b52da2a#gid=0 і викладачі будуть давати відповіді в fl-9/Questions румі.

**Comment by ipavlyuk** [comment]
Сьогодні більш організаційні питання, а от наступна Q&A сесія вже буде стосуватися домашніх завдань і лекції, чим далі тим більше питань буде

**Comment by olehmelnyk** [comment]
а тепер дивіться який фінт ушамі:

1) заходите на сторінку гітову де багато "питань" - наприклад сюди - https://github.com/facebook/create-react-app/issues
2) відкриваєте консоль браузера (на вінді F12) і вставляєте туди такий говно-код
`[...document.querySelectorAll('.h4')].forEach(q => console.log(q.textContent))`
3) жмете Enter і отримуєте список всіх питань на сторінці - можна копіювати в чат Questions
4) profit!

**Comment by ipavlyuk** [comment]
Старости щось так довго рахують + і -, шо думаю з цього нічого не вийде (

**Comment by olehmelnyk** [comment]
сьогодні буде гугдокс а далі буде видно

**Comment by ipavlyuk** [comment]
Та за сьогодні це зрозуміло )

**Comment by andrii1509** [comment]
[...document.getElementsByClassName("h4")].forEach(z =>{
	console.log(z.innerText)
})

**Comment by andrii1509** [comment]
давайте знайомитись поближче... хтось  вже працював з фронтом, беком, фреймворками (Angular, React, Vue, Node  і т. д.)???
