### ISSUE TITLE
<html> без атрибута "lang" не проходить валідацію

### ISSUE THREAD

**Issue by olehmelnyk** [olehmelnyk/fl9-Questions#2]
валідатор просить `<html lang="en">` - без `lang` не проходить валідація... додавати чи ігнорити? - ось у чому питання 🤔💀

**Comment by kokc12** [comment]
В завданні чітко вказано місце де можна редагувати код. Я не добавляв атрибут lang.

**Comment by olehmelnyk** [comment]
але в завданні також чітко вказано, що треба виправити всі помилки які виявив валідатор

**Comment by sheljak** [comment]
Я поставив lang, але то вапрос...

**Comment by pavlosuperhero** [comment]
На рахунок мови - lang ставиться не тільки в html тезі а ще й в таких чудесних штуках як:
```
<a>, <abbr>, <acronym>, <address>, <applet>, <area>, <b>, <basefont>, <bdo> <bgsound>, <big>, <blockquote>, <body>, <br>, <button>, <caption>, <center>, <cite>, <code>, <col>, <colgroup>, <dd>, <del>, <dfn>, <dir>, <div>, <dl>, <dt>, <em>, <embed>, <fieldset>, <font>, <form>, <frame>, <h1>, <h2>, <h3>, <h4>, <h5>, <h6>, <hr>, <i>, <iframe>, <img>, <input>, <ins>, <isindex>, <kbd>, <label>, <legend>, <li>, <link>, <map>, <marquee>, <menu>, <nobr>, <object>, <ol>, <option>, <p>, <plaintext>, <pre>, <q>, <s>, <samp>, <select>, <small>, <span>, <strike>, <strong>, <sub>, <sup>, <table>, <tbody>, <td>, <textarea>, <tfoot>, <th>, <thead>, <tr>, <tt>, <u>, <ul>, <var>, <wbr>, <xmp>.
```
Ресурс - http://htmlbook.ru/html/attr/lang

З цього виникає питання - чи ту хрін пхати всюди, чи запхати в html?

**Comment by olehmelnyk** [comment]
по ідеї - основну мову сторінки треба писати в html, а якшо є іншомовні вставки - то можна завертати в спан і йому вказувати мову

**Comment by pavlosuperhero** [comment]
Дякую за едіт!

**Comment by pavlosuperhero** [comment]
Виглядає як або хтось помилився (хтось зі стажем в Епамі) або це частина завдання...

**Comment by olehmelnyk** [comment]
та, то або супер-челедж, або вони не думали шо ми такі задроти і будем за то паритись)))

**Comment by pavlosuperhero** [comment]
Для мене це важливо знати, коли я вчив Си, я постійно стикався з тим, що якась крапочка серед 2000+ строк коду, на загальний процес не впливала, але пам'яті грохала, що сервер лягав, завдання я провалив, як наслідок я тут а не в Києві )
