### ISSUE TITLE
Навігація: "nav > ul > li > a" чи "nav > a"

### ISSUE THREAD

**Issue by olehmelnyk** [olehmelnyk/fl9-Questions#3]
менюшка - семантично має бути `nav > ul > li > a` але без CSS вилазаять булєти... писати просто `nav > a`?

**Comment by StadnykYura** [comment]
@olehmelnyk 
якорі

**Comment by stelmakhivan** [comment]
Валідатор доречі нормально пропускає nav > a....
Ось тут також знайшов приклад  https://www.w3schools.com/tags/tag_nav.asp

**Comment by StadnykYura** [comment]
Закривай)
