### ISSUE TITLE
blockquote: робити "як краще [по стандарту]" чи "як на картинці"?

### ISSUE THREAD

**Issue by olehmelnyk** [olehmelnyk/fl9-Questions#4]
blockquote "по феншую" не получається... в ідеалі має бути:
```
<blockquote cite="...">
    <p>
        ...
    </p>
    <footer>
        &mdash; <cite><a href="...">Elon Musk</a></cite>
    </footer>
</blockquote>
```
але як пишеш footer в середині blockquote застосовуються стилі головного футера сторінки)))
 + виходить семантично правильніше, але не зовсім так як на картинці - тепер не знаю як з тим жити 🤯🤣

**Comment by StadnykYura** [comment]
@olehmelnyk 
де ти знайшов такий конвешн? 
1) футер в блокКвот?
2) в <cite> огорнув якір з ім'ям того дядька? 
я шось такого не спостерігав.

**Comment by olehmelnyk** [comment]
@StadnykYura блін, ну ти мене і налякав)) пам'ятаю ж шо футер може бути [у всіх?] блочних семантичних тегів

- [HTML5Doctor](http://html5doctor.com/cite-and-blockquote-reloaded/)

- [stackoverflow](https://stackoverflow.com/a/27297189)
- і т.п.

**Comment by StadnykYura** [comment]
@olehmelnyk Дякую

**Comment by DmytroVoytovych** [comment]
народ в мене при валідації blockquote видає Element blockqoute not allowed as child of element div in this context, як вирішити?

**Comment by olehmelnyk** [comment]
покажи стрктуру - шо в шо вкладено

**Comment by DmytroVoytovych** [comment]
```
<div id="blockquotes">
                  <h2>Blockquotes</h2>
                  <p>Let’s keep it simple. ..</p>
                  <blockqoute> </blockqoute>;
<a href="#"><i>Elon Musk</i></a>
              </div>
```

**Comment by olehmelnyk** [comment]
а має бути
```
<section id="blockquotes">
    <h2>Blockquotes</h2>
    <p>Let’s keep it simple...</p>
    <blockquote>
        <p>
            ...
        </p><a href="">Elon</a>
    </blockquote>
</section>
```

**Comment by pavlosuperhero** [comment]
І як, вирішилась проблема з футером? Бо думаю забити, тай не ставити його там в blockquotes

**Comment by DmytroVoytovych** [comment]
все інші блоки в мене в дівках, я так розумію тут просто дівку на секшин змінити?

**Comment by DmytroVoytovych** [comment]
в мене футер нижче за blockquotes

**Comment by pavlosuperhero** [comment]
Ну, якщо вірити Мануалам, то в принципі так, але section - то семантичний поділ сторінки, div не несе семантики, так що уважно там, пройди ще раз валідацію )

**Comment by DmytroVoytovych** [comment]
я пробував

**Comment by olehmelnyk** [comment]
той валідатор якийсь вгашений)) той кусок шо я скопіював зі свого коду не проходить валідацію і видаєе таку ж помилку з blockquote, але якшо валідувати весь HTML від початку і до кінця то ніяких помилок в blockquote нема

**Comment by DmytroVoytovych** [comment]
а вмене при валідейті свього коду така штука

**Comment by DmytroVoytovych** [comment]
The blockquote element represents content that is quoted from another source, optionally with a **citation** which must be within a **footer** or **cite** element, and optionally with in-line changes such as annotations and abbreviations.

**Comment by DmytroVoytovych** [comment]
Here the attribution is given in a footer after the quoted text, and metadata about the reference has been added using the RDFA Lite syntax. [rdfa-lite] 
```
<blockquote>
  <p>... she said she would not sign any deposition containing the word "amorous" instead of "advances". For her the difference was of crucial significance, and one of the reasons she had separated from her husband was that he had never been amorous but had consistently made advances.</p>
  <footer typeof="schema:Book">
    <span property="schema:author">Heinrich Böll</span>,
    <span property="schema:name">The Lost Honor of Katharina Blum</span>,
    <span property="schema:datePublished">January 1, 1974</span>
  </footer>
</blockquote>
```

**Comment by DmytroVoytovych** [comment]
все одно воно свариться на "blockquotes", в мене код весь вкладений в `<div id="content" role="main"> </div>`! Одним словом не знаю як це виправити!

**Comment by DmytroVoytovych** [comment]
Але футор я вклав в блокквот, як було рекомендовано

**Comment by DmytroVoytovych** [comment]
це issue можна закрити, але мені цікаво як у випадку коли footer вкласти в `<blockquote>` то він займе всю ширину блоку `<blockquote>`, а в зразку є ширшим?

**Comment by olehmelnyk** [comment]
та хай би займав - там CSS кривий просто))

**Comment by DmytroVoytovych** [comment]
бо є рекомендованим вкладати в `<blockquote>` цитати та футер, але тоді не відповідність зразку(((

**Comment by olehmelnyk** [comment]
думаю в тому і фішка - подивитись чи ми зробим по стандарту чи як на картинці - CSS`ом відображення можна як хочеш міняти, а стандарт ніхто не відміняв

**Comment by DmytroVoytovych** [comment]
підтримую

**Comment by ipavlyuk** [comment]
Думаю за це треба запитати, бо в завданні написано зробити як на картинці, але це і водночас має бути правильно, а тут виходить або одне або інше

**Comment by DmytroVoytovych** [comment]
в разі чого в нас на це будуть свої аргументи з ресурсів, які всі рекомендують при вивчені HTML

**Comment by ipavlyuk** [comment]
Ну тобі поставлять оцінку і не дуже то і будуть питати ))
Хіба якщо вже зовсім зле і пройдеш тестування, то можуть з тобою за це на співбесіді поговорити ))

**Comment by ipavlyuk** [comment]
І ще перед тим як відправляти це питання в доку його треба норм сформулювати ))
Бо не впевнена, що викладачі зрозуміють, шо ми маємо на увазі під ''blockquote не "по феншую"'' ))

**Comment by StadnykYura** [comment]
вже говорили багато за blockquote, але як ви вирішили зробити? так як на картинці? чи правильно?
ось мій blockquote:
```
<blockquote cite="..........."> 
    <p>"If you go back a few hundred years, ............................ These are all things that would have been 
            considered magic a few hundred years ago."
       <br/> 
       <a href="#">Elon Musk</a> 
    </p>
 </blockquote>
```

@olehmelnyk ?
бо з `<cite>` все сложно), воно не стайлиться, мабуть через файл css

**Comment by olehmelnyk** [comment]
для бота - зробив як на картинці,
а для людей - залишив коментар шо знаю кращий спосіб + посилання

думаю це найправильніший спосіб
