### ISSUE TITLE
<h1> всередині <article> не проходить валідацію

### ISSUE THREAD

**Issue by olehmelnyk** [olehmelnyk/fl9-Questions#5]
валідатору чомусь не подобається `<h1>` всередині `<article>` - по моєму він просто тупить - писати `<h2>` шоб його заткнути? 🤐

**Comment by StadnykYura** [comment]
а ну покаж код?* де в тебе артикл з h1?

**Comment by olehmelnyk** [comment]
```
              <h2>Text formats</h2>
            
              <h3>Article Text</h3>
              <article>
                <h2>Article title</h2><!-- because validator didn't like <h1> in <article> :) -->
                <p>Article description</p>
              </article>
```

**Comment by StadnykYura** [comment]
h1 можна лише один раз в документі, і він в нас в хедері

**Comment by olehmelnyk** [comment]
в HTML5 - h1 може бути у всіх семантичних елементів, типу section, article, aside і т.п.

**Comment by StadnykYura** [comment]
Я старої закалки трохи), перечитав про це статтю.
 Але якщо взяти те що в мене це в секшині, потім іде h2, далі артікл в секшині, і в ньому h1 воно якось не по феншую(

**Comment by StadnykYura** [comment]
Та й розмір h1 хіба буде таким же як в темплейті? Бо зараз не біля ноута

**Comment by olehmelnyk** [comment]
так от в **асайді** якарз пишуть шо вони зробили розмір h1 i h2 однаковими...
та й в тому фішка тої нової семантичності шо якшо кожен секшн чи артікл - це самостійна частина в якій можуть бути свої хедери, футери, h1 і все решту

**Comment by StadnykYura** [comment]
А той текст шо вони написали на початку пейджі, шо h1 єдине на цілу пейджу, не враховувати? Це просто заплутування?

**Comment by olehmelnyk** [comment]
ну наскільки я знаю - в HTML5 на всю сторінку - є один, головний h1 тег, але секшени/артікли теж можуть мати свій внутрішній заголовок h1

**Comment by StadnykYura** [comment]
Та я вже зрозумів це), і почитав статейку "чому").
Але для впевненості  як реально на продакшині потрібно запитати в них

**Comment by Stegura** [comment]
Валідатор видеє не ерор а варнінг тому, це не є помилкою

**Comment by olehmelnyk** [comment]
в ТЗ не вказано виправляти тільки помилки - там треба фіксити всі **проблеми** (-	Fix all issues which was found by w3org Markup Validation Service )

**Comment by Stegura** [comment]
Тоді ок, що робити з Consider adding a lang attribute to the html start tag to declare the language of this document., якщо він за межами нашого To DO #2

**Comment by olehmelnyk** [comment]
ну так для відповіді на це питання я і підняв цю тему)) або не виходити за рамки ToDo або фіксити все що знайшов валідатор - якось так ;) #2

**Comment by Stegura** [comment]
крім того якщо виправити на h2 то розмір Article title змінюється, методом підбору і перевірки в інших браузерах підходить h3

**Comment by olehmelnyk** [comment]
CSS'ом завжди можна зробити шоб було як на картинці (типу як дизайнер задумав) але HTML розмітку краще таки робити притримуючись стандартів і логіки

**Comment by ipavlyuk** [comment]
Тут h1 немає потреби юзати двічі, як на мене
І по розміру з картинкою не сходиться і валідатор свариться )
