### ISSUE TITLE
<aside> перед <main>

### ISSUE THREAD

**Issue by olehmelnyk** [olehmelnyk/fl9-Questions#6]
по логіці, виглядає так ніби там `<aside>` перед `<main>` шо не є гуд (на флекбоксі би порішалось) - чи то я вже занадто упоровся з семантикою? 😜

**Comment by tarasroz** [comment]
може й так би хотілося зробити, але пише робити ДЗ в -

**Comment by tarasroz** [comment]
TODO: Content goes here

**Comment by olehmelnyk** [comment]
та воно одному другому не заважає - є клас .main а є семантичний тег `<main>`
