### ISSUE TITLE
HTML5 Support (HTML5 shiv)

### ISSUE THREAD

**Issue by oksanadrul** [olehmelnyk/fl9-Questions#7]
Чи можемо ми додавати підтримку html5 для старих браузерів

**Comment by olehmelnyk** [comment]
типу чи можна писати `<article>, <nav>, <section>` для старих Internet Explorer?
так, можна, підключивши JS: `<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>`

**Comment by oksanadrul** [comment]
в описі до домашнього завдання написано
1 - ми маємо додавати теги та атрибути
2- писати свій код в відповідному місці

якщо ми додаємо:
`<html lang="en">`  - це атрибут 
але він доданий не в тому місці де вказали (і як бот буде оцінювати нашу ініціативу)

те  саме з 
``
по суті ми підключаємо ще один додатковий стиль (це не тег і не атрибут )

**Comment by olehmelnyk** [comment]
думаю тим не треба паритись на даному етапі, екслорер вимер, а останні версії 10 і 11 повинні підтримувати ці теги

**Comment by oksanadrul** [comment]
https://frontendlabepam.github.io/FL_Online/02_html/#39
а в презентації його згадують ((((

**Comment by olehmelnyk** [comment]
хм, тоді давай запитаєм в експерта)

**Comment by olehmelnyk** [comment]
І це не стиль - це коментар, який розуміє тільки IE

**Comment by ipavlyuk** [comment]
Цього не потрібно робити, потрібно чітко притримуватись домашнього завдання і не придумувати додаткові завдання, якби це було необхідно це було б вказано як одне з завдань )

**Comment by olehmelnyk** [comment]
думаю там спеціально зроблені "пасхалки" шоб подивитись чи ми їх знайдем і виправим... або я просто буйнопомішаний 🤪

**Comment by ipavlyuk** [comment]
Це ти про lang? Я думаю його просто провтикали
А на рахунок підтримки ІЕ, це справді зайве, якщо задасте це питання я думаю, що відповідь буде, щось типу ''Не шукайте собі зайвих завдань''

**Comment by olehmelnyk** [comment]
якби один завтик був то ок, але я їх декілька найшов, такшо не знаю як то всьо розуміти)

**Comment by ipavlyuk** [comment]
Я тобі скажу, що це ще тільки початок, тільки перша домашка )))
